CREATE TABLE IF NOT EXISTS Settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  settings jsonb
)

CREATE POLICY "Enable access to all users" ON public.Settings FOR
SELECT
  USING (true);

CREATE POLICY "Superadmin can update settings" ON public.Settings FOR
UPDATE
  USING (auth.role() = 'superadmin') WITH CHECK (auth.role() = 'superadmin');